name: aws_chime_plugin
description: A new flutter plugin for AWS Chime SDK.
version: 0.0.1
homepage: https://github.com/Agilefreaks/aws_chime_plugin

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.free.aws_chime_plugin
        pluginClass: AwsChimePlugin
      ios:
        pluginClass: AwsChimePlugin